name: Subdomain_Finder
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOMAIN: 'knb.nl'

jobs:
  subdomains:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 
    
    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        sudo apt-get install jq -y 
      shell: bash

    - name: Run Subfinder
      run: |
        subfinder -d $DOMAIN -o sorted_domains.txt
      shell: bash
   
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Subdomains results
        path: |
           sorted_domains.txt

  HTTPX:
    runs-on: ubuntu-latest
    needs: subdomains
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: Subdomains results
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 

    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest 
      shell: bash

    - name: HTTPX_Detailed 
      run: |
        cat sorted_domains.txt | httpx -sc -title -server -fr -td | tee -a detailed_httpx.txt
      shell: bash
    - name: HTTPX_Live for endpoint
      run: | 
        cat sorted_domains.txt | httpx -mc 200 | tee -a 200httpx.txt
      shell: bash
    - name: httpx for all - no filtering
      run: |
        cat sorted_domains.txt | httpx | tee -a normalhttpx.txt
      shell: bash 

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: HTTPX results
        path: |
          detailed_httpx.txt
          200httpx.txt
          normalhttpx.txt
          
  HostHeader Injection:
    runs-on: ubuntu-latest
    needs: HTTPX
    steps:
    - name: Download results
      uses: actions/download-artifact@v2
      with:
        name: HTTPX results

    - name: Install tool from github.com/prakashchand72 
      run: |
        curl https://raw.githubusercontent.com/prakashchand72/hostheaderinjection_finder/main/hostheaderinject -o hostheaderinjection.sh
      shell: bash

    - name: Scanning 
      run: |
        bash hostheaderinjection.sh 200httpx.txt
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: HostHeaderinjection
        path: |
          vulnerable_urls.txt

